import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Contact from "../components/Contact";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pinch of Spice LLC. | ピンチオブスパイス合同会社</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/poc.svg"
          width={184}
          height={29}
          alt="pinch of spice logo"
        />
      </main>

      <Contact />

      <footer className={styles.footer}>
        <p>Copyright© Pinch of Spice LLC. All Rights Reserved</p>
      </footer>
    </div>
  );
};

export default Home;
